---
- name: Reload systemd
  tags:
    - systemd
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: system

- name: Restart systemd-journald
  tags:
    - systemd
  become: true
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted

- name: Restart systemd-logind
  tags:
    - systemd
  become: true
  ansible.builtin.systemd_service:
    name: systemd-logind
    state: restarted
...
