---
dependencies:
  - role: device_info
    tags: mount
galaxy_info:
  role_name: mount
  author: Taylor Kimball
  description: Control active and configured mount points
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - linux
    - mount
...
