---
dependencies: []
galaxy_info:
  role_name: dnf_versionlock
  author: Taylor Kimball
  description: DNF versionlock Plugin
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - dnf
    - linux
    - lock
    - plugin
    - version
...
