---
- name: Converge
  hosts: all
  roles:
    - role: systemd
      tags:
        - molecule-idempotence-notest

    - role: systemd
      systemd_hostnamectl:
        set-deployment: production
        set-hostname: "{{ inventory_hostname }}"
        set-icon-name: computer-server
      systemd_journald:
        Audit:
        Compress: true
      systemd_localectl:
        set-locale: LANG=en_US.UTF-8
      systemd_logind:
        KillOnlyUsers:
          - vagrant
      systemd_system:
        CrashReboot: false
      systemd_timedatectl:
        set-local-rtc: '0'
        set-ntp: '1'
        set-timezone: America/Los_Angeles
      systemd_user:
        LogColor: true
        LogTime: false
...
