---
dependencies:
  - role: epel
    tags: transmission_daemon
    when: ansible_os_family == 'RedHat'
galaxy_info:
  role_name: transmission_daemon
  author: Taylor Kimball
  description: A fast, easy, and free bittorrent client
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - daemon
    - linux
    - torrent
    - transmission
...
