---
dependencies: []
galaxy_info:
  role_name: systemd
  author: Taylor Kimball
  description: A system and service manager for Linux
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - hostnamectl
    - journald
    - linux
    - localectl
    - logind
    - timedatectl
    - systemd
...
