---
dependencies: []
galaxy_info:
  role_name: systemd
  author: Taylor Kimball
  description: A system and service manager for Linux
  license: GPLv3
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - linux
    - systemd
...
