---
dependencies:
  - role: epel
    tags: rclone
    when: ansible_os_family == 'RedHat'
galaxy_info:
  role_name: rclone
  author: Taylor Kimball
  description: A command-line program to manage files on cloud storage
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - '9'
  galaxy_tags:
    - cloud
    - rclone
    - storage
...
