---
dependencies: []
galaxy_info:
  role_name: speedtest
  author: Taylor Kimball
  description: Official Ookla Speedtest CLI
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - linux
    - ookla
    - speedtest
...
