---
dependencies: []
galaxy_info:
  role_name: kopia
  author: Taylor Kimball
  description: Fast and secure open-source backup software
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - kopia
    - linux
...
