---
dependencies: []
galaxy_info:
  role_name: openssh_server
  author: Taylor Kimball
  description: OpenSSH SSH daemon
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - linux
    - openssh
    - server
    - ssh
...
