---
dependencies:
  - role: docker
    tags: docker_compose
galaxy_info:
  role_name: docker_compose
  author: Taylor Kimball
  description: Run multi-container applications with Docker
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - compose
    - docker
    - linux
...
