---
dependencies: []
galaxy_info:
  role_name: systemd_resolved
  author: Taylor Kimball
  description: A systemd service that provides network name resolution to local applications
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - linux
    - resolved
    - systemd
...
