---
dependencies: []
galaxy_info:
  role_name: sysctl
  author: Taylor Kimball
  description: Configure kernel parameters at runtime
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - kernel
    - linux
    - sysctl
...
