---
dependencies: []
galaxy_info:
  role_name: device_info
  author: Taylor Kimball
  description: Gather information about devices and partitions
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - device
    - linux
    - info
    - partition
...
