---
dependencies:
  - role: epel
    tags: lux
galaxy_info:
  role_name: lux
  author: Taylor Kimball
  description: Lux YUM repository
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - frank
    - linux
    - lux
...
