---
dependencies:
  - role: docker
    tags: docker_container
galaxy_info:
  role_name: docker_container
  author: Taylor Kimball
  description: Manage docker containers
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - container
    - docker
    - linux
...
