---
dependencies: []
galaxy_info:
  role_name: setup
  author: Taylor Kimball
  description: Configure setup package contents
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - alias
    - environment
    - hosts
    - hostname
    - motd
    - linux
    - profile
...
