---
- name: Converge
  hosts: all
  roles:
    - role: systemd_resolved
      tags:
        - molecule-idempotence-notest

    - role: systemd_resolved
      systemd_resolved_conf:
        Cache: false
        DNS:
          - 8.8.8.8#dns.google
          - 8.8.8.8#dns.google
        FallbackDNS:
          - 1.1.1.1#cloudflare-dns.com
          - 1.0.0.1#cloudflare-dns.com
        DNSOverTLS: true
        DNSSEC: true
        LLMNR: false
...
