---
- name: Verify
  hosts: all
  tasks:
    - name: Ensure systemd service facts are gathered
      tags:
        - systemd_resolved
      ansible.builtin.service_facts:

    - name: Ensure systemd service facts are verified
      tags:
        - systemd_resolved
      ansible.builtin.assert:
        that:
          - services['systemd-resolved.service'] is defined
          - services['systemd-resolved.service'].state == 'running'
          - services['systemd-resolved.service'].status == 'enabled'
...
