---
dependencies: []
galaxy_info:
  role_name: elrepo
  author: Taylor Kimball
  description: ELRepo Project
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - elrepo
    - linux
...
