---
remi_baseurl: 'https://rpms.remirepo.net'
remi_packages: []
remi_release: "remi-release-{{ ansible_distribution_major_version }}.rpm"
remi_repositories:
  - name: remi-modular
    state: enabled
  - name: remi-safe
    state: enabled
...
