---
dependencies:
  - role: epel
    tags: monit
galaxy_info:
  role_name: monit
  author: Taylor Kimball
  description: Utility for monitoring services on a Unix system
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - linux
    - monit
...
