---
dependencies:
  - role: docker
    tags: docker_network
galaxy_info:
  role_name: docker_network
  author: Taylor Kimball
  description: Manage docker networks
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - docker
    - linux
    - network
...
