---
dependencies: []
galaxy_info:
  role_name: cloudflare_warp
  author: Taylor Kimball
  description: Manage cloudflare warp tunnels
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - '8'
        - '9'
        - '10'
  galaxy_tags:
    - cloudflare
    - linux
    - warp
...
