---
dependencies: []
galaxy_info:
  role_name: postfix
  author: Taylor Kimball
  description: A free and open-source mail transfer agent
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - linux
    - mail
    - mta
    - postfix
...
