---
dependencies: []
galaxy_info:
  role_name: git
  author: Taylor Kimball
  description: Clone git repositories
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - git
    - linux
...
