---
dependencies: []
galaxy_info:
  role_name: nscd
  author: Taylor Kimball
  description: Name service cache daemon
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - linux
    - nscd
...
