---
dependencies: []
galaxy_info:
  role_name: docker
  author: Taylor Kimball
  description: Docker Community Edition
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - docker
    - linux
...
